### ISSUE TITLE
Adding. hover affects on links

### ISSUE THREAD

**Issue by theNaut1lus** [TheAlgorithms/website-old#27]
@AnshulMalik 
As a design inclusion the website would look good if we added svg icons of each programming language before it's list name.
It would really increase the overall look of the website.
We can use flaticon or font awesome for the same.
I would also love to work on this as my first contribution here. 😃 🥇

**Comment by AnshulMalik** [comment]
@co16353sidak, that's a nice idea!
For now, our goal is to make it as light weight as possible, so we try to avoid any libraries.

It would be awesome if we can just grab some svgs and place them nicely :)

**Comment by theNaut1lus** [comment]
@AnshulMalik Thank you!, svg for all language icons are open source and available so won’t be a problem, assign this to me meanwhile let me create a sample send up a PR.

**Comment by theNaut1lus** [comment]
Please review @AnshulMalik

**Comment by AnshulMalik** [comment]
We can use this issue to add that small change as well @co16353sidak .

**Comment by theNaut1lus** [comment]
@AnshulMalik 
Now that I think of it, this would be really better for continuity to let me make a separate issue for this as this would

* let me target a separate issue in the subsequent PR I will make.
* Also adding new changes with different PRs to an existing issue seems to be really counter-productive to the whole concept of GitHub 😄 
* Also as we keep on developing on the website, it would aid any future contributors to find separate issue on this when they blame it in the future

**Comment by AnshulMalik** [comment]
Fine with me :)

**Comment by theNaut1lus** [comment]
Close this one then via my PR. 👍 
I will create a new one
