### ISSUE TITLE
Logo overlaps the content 

### ISSUE THREAD

**Issue by SpaceLenore** [TheAlgorithms/website-old#5]
### Logo overlaps text
The logo overlaps parts of the content on smaller screens (see screenshot)  
There also seems to be a bit of a padding between the element that scrolls and the body element
![screenshot from 2018-10-01 22-41-10](https://user-images.githubusercontent.com/31237758/46314833-ee30ab00-c5cb-11e8-830c-451d68895bde.png)

edit: also the css is slightly difficult to read when semi-minified. Consider beautifying it for readability.

I'll submit a PR with my fix for it if that is okay

**Comment by ghost** [comment]
I can work on this issue.

**Comment by SpaceLenore** [comment]
@shaileshshivam Feel free to solve it as well, I submitted my Pull Request #6 for it but the more the merrier :D

**Comment by aniketdvd** [comment]
I did it! please check my pull request! CHEERS!
for hacktoberfest2018

**Comment by adsingh14** [comment]
Fixed in the following PR: https://github.com/TheAlgorithms/website/pull/8/commits/d2bddf23bb0dcb012cdd0ca98761716423b2b5e0

**Comment by AnshulMalik** [comment]
Not valid anymore
